language: php
php:
  - 5.6

branches:
  only:
    - master

before_install:
  - composer install --prefer-dist --no-interaction

script: phpunit  -c phpunit.travis.xml

notifications:
  mail: p.scheit@ps-webforge.com
